import React from "react";
import {
  Archive,
  ArchiveX,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpDown,
  ArrowUpToLine,
  Bell,
  BellOff,
  BellPlus,
  BellRing,
  Calculator,
  CalendarArrowUp,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CalendarSync,
  CircleDot,
  ClipboardCopy,
  GitBranch,
  Hourglass,
  ListChecks,
  ListTree,
  Repeat,
  CornerLeftUp,
  Copy,
  CopyPlus,
  Eraser,
  FilePlus,
  FolderPlus,
  Hash,
  Layers,
  Link2,
  ListPlus,
  ListX,
  Mail,
  MessageCircle,
  MessageSquare,
  Newspaper,
  PenLine,
  SquareArrowOutUpRight,
  Tags,
  TextCursorInput,
  Timer,
  Trash2,
  UserMinus,
  UserPlus,
  Unplug,
  Users,
  Webhook,
  type LucideIcon,
} from "lucide-react";
import type { ActionPickerId } from "./automationCatalog";

/** The colored square in front of each entry of the "Then do this" menu, like monday's action list. */
const ACTION_ICONS: Record<ActionPickerId, { icon: LucideIcon; color: string }> = {
  move_to_group: { icon: ArrowRight, color: "#a25ddc" },
  notify_person: { icon: Bell, color: "#037f4c" },
  change_status: { icon: CircleDot, color: "#0073ea" },
  create_subitem: { icon: ListPlus, color: "#fdab3d" },
  set_date: { icon: CalendarDays, color: "#00c875" },
  create_item: { icon: FilePlus, color: "#579bfc" },
  duplicate_item: { icon: Copy, color: "#579bfc" },
  archive_item: { icon: Archive, color: "#676879" },
  delete_item: { icon: Trash2, color: "#e2445c" },
  post_update: { icon: MessageSquare, color: "#ff7575" },
  set_column_value: { icon: PenLine, color: "#0086c0" },
  clear_column: { icon: Eraser, color: "#9d99b9" },
  adjust_number: { icon: Calculator, color: "#784bd1" },
  assign_person: { icon: UserPlus, color: "#66ccff" },
  unassign_people: { icon: UserMinus, color: "#c4c4c4" },
  send_email: { icon: Mail, color: "#bb3354" },
  slack_notify_person: { icon: MessageCircle, color: "#4a154b" },
  slack_notify_channel: { icon: Hash, color: "#4a154b" },
  move_to_board: { icon: ArrowRightLeft, color: "#225091" },
  shift_date: { icon: CalendarArrowUp, color: "#00a359" },
  set_date_from_column: { icon: CalendarSync, color: "#00a359" },
  ensure_date_after: { icon: CalendarClock, color: "#00a359" },
  set_timeline: { icon: CalendarRange, color: "#00a359" },
  create_group: { icon: FolderPlus, color: "#784bd1" },
  duplicate_group: { icon: CopyPlus, color: "#784bd1" },
  archive_group: { icon: ArchiveX, color: "#784bd1" },
  copy_column_value: { icon: ClipboardCopy, color: "#0086c0" },
  time_tracking: { icon: Timer, color: "#ff642e" },
  connect_items: { icon: Link2, color: "#225091" },
  notify_team: { icon: Users, color: "#037f4c" },
  send_webhook: { icon: Webhook, color: "#323338" },
  wait: { icon: Hourglass, color: "#ff9f1a" },
  shift_dependents: { icon: GitBranch, color: "#00a359" },
  assign_round_robin: { icon: Repeat, color: "#66ccff" },
  set_subitems_value: { icon: ListTree, color: "#fdab3d" },
  set_parent_value: { icon: CornerLeftUp, color: "#fdab3d" },
  add_checklist_items: { icon: ListChecks, color: "#00c875" },
  rename_item: { icon: TextCursorInput, color: "#579bfc" },
  change_values: { icon: Tags, color: "#0086c0" },
  update_connected_items: { icon: Unplug, color: "#225091" },
  group_items: { icon: Layers, color: "#784bd1" },
  subscribe_people: { icon: BellPlus, color: "#037f4c" },
  unsubscribe_people: { icon: BellOff, color: "#676879" },
  notify_subscribers: { icon: BellRing, color: "#037f4c" },
  clear_subitems: { icon: ListX, color: "#fdab3d" },
  convert_subitem: { icon: SquareArrowOutUpRight, color: "#fdab3d" },
  send_digest: { icon: Newspaper, color: "#bb3354" },
  move_item_position: { icon: ArrowUpToLine, color: "#579bfc" },
  sort_group: { icon: ArrowUpDown, color: "#784bd1" },
};

export function ActionIcon({ id, size = 20 }: { id: ActionPickerId; size?: number }) {
  const { icon: Icon, color } = ACTION_ICONS[id];
  return (
    <span className="flex flex-none items-center justify-center rounded-[4px] text-white" style={{ background: color, width: size, height: size }} aria-hidden="true">
      <Icon size={Math.round(size * 0.62)} strokeWidth={2.2} />
    </span>
  );
}
